import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import type { Metadata } from "next";
import { Mulish, Open_Sans, Inter, Teko } from "next/font/google";
import { Theme, ThemePanel } from "@radix-ui/themes";
import "./globals.css";
import Navbar from "./Navbar";
import { SkeletonTheme } from "react-loading-skeleton";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const openSans = Open_Sans({
    subsets: ["latin"],
    display: "swap",
});

const mulish = Mulish({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-mulish",
});

const teko = Teko({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-teko",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={teko.variable}>
                <Theme appearance="dark" accentColor="amber">
                    <SkeletonTheme baseColor="#151515" highlightColor="#525252">
                        <Navbar />
                        <main className="p-5">{children}</main>
                    </SkeletonTheme>
                </Theme>
            </body>
        </html>
    );
}
